import numpy as np
from solver import solve, get_initial_warm_start
from plotter import plot_solution_in_statespace_and_control, plot_solution_in_state_space
from misc import calculate_arc_length

if __name__ == "__main__":
    eps = 1e-2
    delta = 1e-2

    x0 = np.array([[2], [0], [np.pi/2]])
    xf = np.array([[-2], [0]])

    constraint = {
        "u1_min": -1,
        "u1_max": 1,
        "u2_min": -1,
        "u2_max": 1
    }

    x_opt, u_opt = solve(x0, xf, constraint, get_initial_warm_start(x0, xf), eps, delta)

    plot_solution_in_state_space(x_opt,
                                 "Path generated by solver - State Space",
                                 np.round(calculate_arc_length(x_opt), 2),
                                 eps,
                                 delta)

    plot_solution_in_statespace_and_control(x_opt,
                                            u_opt,
                                            arc_length=np.round(calculate_arc_length(x_opt), 2),
                                            eps=eps,
                                            delta=delta)
